In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
print("Hello World")

Hello World


In [2]:
df_yugi = pd.read_csv('dbs/yugi_comp.csv')
df_yugi = df_yugi.drop(['name'], axis=1)
df_yugi = df_yugi[df_yugi['text'].notna()]
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN  
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN  
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play  
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN  
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN

In [20]:
def getTribe(row):
    #if row["card_type"] == "monster":
    if type(row["type"]) is float:
        return math.nan
    return row["type"].split("/")[0].strip()
    #else:
    #    return math.nan

In [4]:
def getEffect(row):
    if row["card_type"] == "monster":
        typ =  row["type"].split("/")[-1].strip()
        if typ == "Effect":
            return typ
        else:
            return "Normal"
    else:
        return math.nan

In [5]:
extradeckmons = ['Xyz', 'Fusion', 'Synchro', 'Ritual', 'Toon', 'Link', 'Union', 'Gemini', 'Skill']
def getMonsType(row):
    if row["card_type"] == "monster":
        typ =  row["type"].split("/")
        if len(typ) >= 3 and typ[1].strip() in extradeckmons:
            return typ[1].strip()
    else: 
        return row["type"]
    return math.nan

In [21]:
df_yugi['tribe'] = df_yugi.apply(lambda row: getTribe(row), axis=1)
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  \
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play   
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN   

           tribe effect? monsType monsType2 Tuner? Pendulum?  
0  Beast-Warrior  Effect      NaN       NaN    NaN       NaN  
1        Warrior  Effect      Xyz       NaN    NaN       NaN  
2            NaN     NaN      NaN       NaN    NaN       NaN  
3          Fairy  Effect      Xyz       NaN    NaN       NaN  
4         Dragon  Effect      NaN       NaN    NaN       NaN

In [7]:
df_yugi['effect?'] = df_yugi.apply(lambda row: getEffect(row), axis=1)
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  \
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play   
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN   

           tribe effect?  
0  Beast-Warrior  Effect  
1        Warrior  Effect  
2            NaN     NaN  
3          Fairy  Effect  
4         Dragon  Effect

In [8]:
df_yugi['monsType'] = df_yugi.apply(lambda row: getMonsType(row), axis=1)
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  \
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play   
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN   

           tribe effect? monsType  
0  Beast-Warrior  Effect      NaN  
1        Warrior  Effect      Xyz  
2            NaN     NaN      NaN  
3          Fairy  Effect      Xyz  
4         Dragon  Effect      NaN

In [9]:
df_yugi.shape

(11574, 16)

In [10]:
df_yugi["monsType"].unique()

array([nan, 'Xyz', 'Fusion', 'Synchro', 'Ritual', 'Toon', 'Link', 'Union',
       'Gemini', 'Skill'], dtype=object)

In [11]:
extradeckmons = ['Xyz', 'Fusion', 'Synchro', 'Ritual', 'Toon', 'Link', 'Union', 'Gemini', 'Skill']

othertype  = ['Spirit', 'Continuous Spell' 'Field Spell','Flip','Continuous Trap']

def getMonsType2(row):
    monst = ""
    if type(row["type"]) is float:
        return math.nan
    #print(row["type"])
    for word in row["type"].split("/"):
            if word.strip() in othertype:
                monst += word.strip() 
    if monst == "":
        return math.nan
    else:
        return monst

In [12]:
def getMonsType3(row):
    if row["card_type"] == "monster":
        typ =  row["type"].split("/")
        for ty in typ:
            typp = ty.strip()
            if typp == "Tuner":
                return "Tuner"
        
    return math.nan

In [13]:

def getMonsType4(row):
    if row["card_type"] == "monster":
        typ =  row["type"].split("/")
        for ty in typ:
            typp = ty.strip()
            if typp == "Pendulum":
                return "Pendulum"
        
    return math.nan

In [14]:
df_yugi['monsType2'] = df_yugi.apply(lambda row: getMonsType2(row), axis=1)
df_yugi['Tuner?'] = df_yugi.apply(lambda row: getMonsType3(row), axis=1)
df_yugi['Pendulum?'] = df_yugi.apply(lambda row: getMonsType4(row), axis=1)
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  \
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play   
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN   

           tribe effect? monsType monsType2 Tuner? Pendulum?  
0  Beast-Warrior  Effect      NaN       NaN    NaN       NaN  
1        Warrior  Effect      Xyz       NaN    NaN       NaN  
2            NaN     NaN      NaN       NaN    NaN       NaN  
3          Fairy  Effect      Xyz       NaN    NaN       NaN  
4         Dragon  Effect      NaN       NaN    NaN       NaN

In [15]:
print(df_yugi["monsType"].unique())
print(df_yugi["monsType2"].unique())
print(df_yugi["Tuner?"].unique())
print(df_yugi["Pendulum?"].unique())

[nan 'Xyz' 'Fusion' 'Synchro' 'Ritual' 'Toon' 'Link' 'Union' 'Gemini'
 'Skill']
[nan 'Flip' 'Spirit' 'Continuous Trap']
[nan 'Tuner']
[nan 'Pendulum']


In [16]:
df_yugi["monsType"].unique()

array([nan, 'Xyz', 'Fusion', 'Synchro', 'Ritual', 'Toon', 'Link', 'Union',
       'Gemini', 'Skill'], dtype=object)

In [17]:

for value in df_yugi["monsType2"].unique():
    if value in types:
        types.remove(value)
types

NameError: name 'types' is not defined

In [22]:
print(df_yugi["tribe"].unique())

['Beast-Warrior' 'Warrior' nan 'Fairy' 'Dragon' 'Aqua' 'Zombie' 'Rock'
 'Beast' 'Insect' 'Sea Serpent' 'Fiend' 'Reptile' 'Plant' 'Thunder'
 'Spellcaster' 'Machine' 'Winged Beast' 'Divine-Beast' 'Rex' 'Dinosaur'
 'Christine' 'Emma' 'Yami Marik' 'Yami Bakura' 'Keith' 'Kaiba' 'Pyro'
 'Weevil' 'Fish' 'Normal' 'Psychic' 'Cyberse' 'Wyrm' 'Yami Yugi' 'Axel'
 'Paradox' 'Jaden & Syrus' 'Jaden' 'Syrus' 'Aster' 'Jesse' 'Mai' 'Pegasus'
 'Ishizu' 'Joey' 'Bastion' 'Chumley' 'Token' 'Espa Roba' 'Odion' 'David'
 'Téa' 'Arkana' 'Andrew' 'Alexis' 'Zane' 'Chazz' 'Dr. Crowler' 'Yubel'
 'Hassleberry' 'Umbra & Lumis' 'Bonz' 'Mako']


In [23]:
df_yugi[df_yugi["tribe"] == "Keith"]

Unnamed: 0                              Name      Rarity  Price  \
126           126                 Spell Proof Armor      Common   6.52   
2150         2150                        Switcheroo  Ultra Rare   5.49   
9647         9647                            Bandit  Super Rare   2.86   
11393       11393  Heavy Metal Raiders (Skill Card)  Ultra Rare   4.30   

       isGood                                               text card_type  \
126      True  Activate this Skill during your Main Phase and...   monster   
2150     True  Activate this Skill during your Main Phase. On...   monster   
9647    False  If your LP are 1500 or less, activate this Ski...   monster   
11393   False  The first time each DARK Machine monster you c...   monster   

                              type family  atk  def  level property  tribe  \
126                  Keith / Skill    NaN  0.0  0.0    0.0      NaN  Keith   
2150                 Keith / Skill    NaN  0.0  0.0    0.0      NaN  Keith   
9647                 Keith / Skill    NaN  0.0  0.0    0.0      NaN  Keith   
11393  Keith / Skill / Field Spell    NaN  0.0  0.0    0.0      NaN  Keith   

      effect? monsType monsType2 Tuner? Pendulum?  
126    Normal      NaN       NaN    NaN       NaN  
2150   Normal      NaN       NaN    NaN       NaN  
9647   Normal      NaN       NaN    NaN       NaN  
11393  Normal    Skill       NaN    NaN       NaN

In [29]:
df_yugi.reset_index(drop=True, inplace=True)


In [30]:
df_yugi

Unnamed: 0                           Name            Rarity  Price  \
0               0        XX-Saber Boggart Knight  Shatterfoil Rare   2.73   
1               1                  Gagaga Cowboy  Shatterfoil Rare   4.68   
2               2              Forbidden Chalice  Shatterfoil Rare   2.09   
3               3               Fairy Cheer Girl  Shatterfoil Rare   2.06   
4               4                Exploder Dragon  Shatterfoil Rare   2.08   
...           ...                            ...               ...    ...   
11569       11642        Herald of Mirage Lights        Ultra Rare   1.55   
11570       11643   Graveyard of Wandering Souls        Ultra Rare   1.39   
11571       11644  Lib the World Key Blademaster        Ultra Rare   3.47   
11572       11645                   Kingyo Sukui        Ultra Rare   1.22   
11573       11646               Skydive Scorcher        Ultra Rare   1.58   

       isGood                                               text card_type  \
0        True  When this card is Normal Summoned: You can Spe...   monster   
1        True  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2        True  Target 1 face-up monster on the field; until t...     spell   
3        True  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4        True  If this card is destroyed by battle and sent t...   monster   
...       ...                                                ...       ...   
11569   False  2 monsters with the same Type and Attribute, e...   monster   
11570   False  If this card is already face-up on the field:\...      trap   
11571   False  2 monsters\n\nCan only be Link Summoned while ...   monster   
11572   False  You can target 1 monster in your opponent's GY...      trap   
11573   False  Target 1 "Elemental HERO" Fusion Monster you c...     spell   

                          type family     atk     def  level    property  \
0       Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1       Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                          NaN    NaN     NaN     NaN    NaN  Quick-Play   
3         Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4              Dragon / Effect  earth  1000.0     0.0    3.0         NaN   
...                        ...    ...     ...     ...    ...         ...   
11569    Fairy / Link / Effect  light   600.0     0.0    0.0         NaN   
11570                      NaN    NaN     NaN     NaN    NaN  Continuous   
11571  Cyberse / Link / Effect  light  2000.0     0.0    0.0         NaN   
11572                      NaN    NaN     NaN     NaN    NaN  Continuous   
11573                      NaN    NaN     NaN     NaN    NaN      Normal   

               tribe effect? monsType monsType2 Tuner? Pendulum?  
0      Beast-Warrior  Effect      NaN       NaN    NaN       NaN  
1            Warrior  Effect      Xyz       NaN    NaN       NaN  
2                NaN     NaN      NaN       NaN    NaN       NaN  
3              Fairy  Effect      Xyz       NaN    NaN       NaN  
4             Dragon  Effect      NaN       NaN    NaN       NaN  
...              ...     ...      ...       ...    ...       ...  
11569          Fairy  Effect     Link       NaN    NaN       NaN  
11570            NaN     NaN      NaN       NaN    NaN       NaN  
11571        Cyberse  Effect     Link       NaN    NaN       NaN  
11572            NaN     NaN      NaN       NaN    NaN       NaN  
11573            NaN     NaN      NaN       NaN    NaN       NaN  

[11574 rows x 19 columns]

## Text

In [24]:
  !pip install --upgrade tensorflow_hub

                                              0.0/100.6 kB ? eta -:--:--
     ----                                     10.2/100.6 kB ? eta -:--:--
     -------------------------------------- 100.6/100.6 kB 1.5 MB/s eta 0:00:00


In [24]:


  import tensorflow_hub as hub

  model = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")
  embeddings = model(["The rain in Spain.", "falls",
                      "mainly", "In the plain!"])

  print(embeddings.shape)  #(4,128)

(4, 128)


In [31]:
embeddings = model(["I like apple pie","I like banana bread","Volcanos are hot"])

In [33]:
embeddings

<tf.Tensor: shape=(3, 128), dtype=float32, numpy=
array([[ 9.90161598e-02, -9.63014737e-02,  9.70842987e-02,
        -3.48744914e-02,  1.13769136e-01,  5.79342954e-02,
        -1.31301492e-01, -9.20234025e-02, -2.01867819e-01,
         8.56303647e-02,  3.92870232e-02, -2.65368462e-01,
        -1.15530007e-03,  7.71153867e-02,  2.06311971e-01,
         5.87709136e-02,  3.33112366e-02,  1.37660235e-01,
         1.05344445e-01, -2.51207501e-02, -1.10472679e-01,
         1.22375771e-01, -5.70573062e-02,  2.56181732e-02,
        -1.19034044e-01, -8.53516906e-02,  5.21319583e-02,
         7.66743869e-02, -1.79157302e-01, -1.56369060e-01,
         1.22116115e-02, -2.57046353e-02, -3.48420627e-03,
         2.04930231e-01,  7.33500347e-02, -7.18652681e-02,
         1.27804130e-01, -2.45568343e-02,  1.19324073e-01,
         2.13116646e-01, -2.29718350e-02, -2.78097466e-02,
        -1.02774948e-01, -2.74781227e-01,  9.47106816e-03,
        -5.88676333e-03, -5.10715842e-02, -4.30089906e-02,
      

In [32]:
import numpy
numpy.dot(embeddings[0],embeddings[1])

1.241015

In [34]:
numpy.dot(embeddings[0],embeddings[2])

0.218732

In [25]:
embeddings=model(df_yugi["text"])

In [26]:
embeddings.shape

TensorShape([11574, 128])

In [27]:
from sklearn.decomposition import PCA

pca_yugi = PCA(n_components=5)
principalComponents_yugi = pca_yugi.fit_transform(embeddings)
principalComponents_yugi

array([[ 0.19008988,  0.24675699,  0.1774311 ,  0.4131257 , -0.10725302],
       [ 0.20476273, -0.02950645, -0.44690601,  0.10647681,  0.2385664 ],
       [ 0.58576469, -0.31468394, -0.03746508,  0.17385659,  0.20930478],
       ...,
       [-0.47194524, -0.11849521,  0.15843191,  0.03263087, -0.02100272],
       [-0.53394323, -0.47551575,  0.27362797, -0.09970592, -0.13590793],
       [-0.03277172, -0.35935366,  0.45918638, -0.39092037, -0.07201906]])

In [28]:
df = pd.DataFrame(principalComponents_yugi, columns=['pca1', 'pca2','pca3','pca4','pca5'])
df

pca1      pca2      pca3      pca4      pca5
0      0.190090  0.246757  0.177431  0.413126 -0.107253
1      0.204763 -0.029506 -0.446906  0.106477  0.238566
2      0.585765 -0.314684 -0.037465  0.173857  0.209305
3      0.258598  0.327643 -0.085230 -0.001137  0.275321
4      0.335081 -0.860984  0.093261 -0.375335 -0.007053
...         ...       ...       ...       ...       ...
11569 -0.589423  0.217515  0.339449 -0.278744 -0.255106
11570 -0.189615 -0.148121  0.086732  0.181361 -0.078621
11571 -0.471945 -0.118495  0.158432  0.032631 -0.021003
11572 -0.533943 -0.475516  0.273628 -0.099706 -0.135908
11573 -0.032772 -0.359354  0.459186 -0.390920 -0.072019

[11574 rows x 5 columns]

In [31]:
df1 = df_yugi.copy()
df1 = df1.join(df)
df1

Unnamed: 0                           Name            Rarity  Price  \
0               0        XX-Saber Boggart Knight  Shatterfoil Rare   2.73   
1               1                  Gagaga Cowboy  Shatterfoil Rare   4.68   
2               2              Forbidden Chalice  Shatterfoil Rare   2.09   
3               3               Fairy Cheer Girl  Shatterfoil Rare   2.06   
4               4                Exploder Dragon  Shatterfoil Rare   2.08   
...           ...                            ...               ...    ...   
11569       11642        Herald of Mirage Lights        Ultra Rare   1.55   
11570       11643   Graveyard of Wandering Souls        Ultra Rare   1.39   
11571       11644  Lib the World Key Blademaster        Ultra Rare   3.47   
11572       11645                   Kingyo Sukui        Ultra Rare   1.22   
11573       11646               Skydive Scorcher        Ultra Rare   1.58   

       isGood                                               text card_type  \
0        True  When this card is Normal Summoned: You can Spe...   monster   
1        True  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2        True  Target 1 face-up monster on the field; until t...     spell   
3        True  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4        True  If this card is destroyed by battle and sent t...   monster   
...       ...                                                ...       ...   
11569   False  2 monsters with the same Type and Attribute, e...   monster   
11570   False  If this card is already face-up on the field:\...      trap   
11571   False  2 monsters\n\nCan only be Link Summoned while ...   monster   
11572   False  You can target 1 monster in your opponent's GY...      trap   
11573   False  Target 1 "Elemental HERO" Fusion Monster you c...     spell   

                          type family     atk  ...  effect?  monsType  \
0       Beast-Warrior / Effect  earth  1900.0  ...   Effect       NaN   
1       Warrior / Xyz / Effect  earth  1500.0  ...   Effect       Xyz   
2                          NaN    NaN     NaN  ...      NaN       NaN   
3         Fairy / Xyz / Effect  light  1900.0  ...   Effect       Xyz   
4              Dragon / Effect  earth  1000.0  ...   Effect       NaN   
...                        ...    ...     ...  ...      ...       ...   
11569    Fairy / Link / Effect  light   600.0  ...   Effect      Link   
11570                      NaN    NaN     NaN  ...      NaN       NaN   
11571  Cyberse / Link / Effect  light  2000.0  ...   Effect      Link   
11572                      NaN    NaN     NaN  ...      NaN       NaN   
11573                      NaN    NaN     NaN  ...      NaN       NaN   

      monsType2 Tuner? Pendulum?      pca1      pca2      pca3      pca4  \
0           NaN    NaN       NaN  0.190090  0.246757  0.177431  0.413126   
1           NaN    NaN       NaN  0.204763 -0.029506 -0.446906  0.106477   
2           NaN    NaN       NaN  0.585765 -0.314684 -0.037465  0.173857   
3           NaN    NaN       NaN  0.258598  0.327643 -0.085230 -0.001137   
4           NaN    NaN       NaN  0.335081 -0.860984  0.093261 -0.375335   
...         ...    ...       ...       ...       ...       ...       ...   
11569       NaN    NaN       NaN -0.589423  0.217515  0.339449 -0.278744   
11570       NaN    NaN       NaN -0.189615 -0.148121  0.086732  0.181361   
11571       NaN    NaN       NaN -0.471945 -0.118495  0.158432  0.032631   
11572       NaN    NaN       NaN -0.533943 -0.475516  0.273628 -0.099706   
11573       NaN    NaN       NaN -0.032772 -0.359354  0.459186 -0.390920   

           pca5  
0     -0.107253  
1      0.238566  
2      0.209305  
3      0.275321  
4     -0.007053  
...         ...  
11569 -0.255106  
11570 -0.078621  
11571 -0.021003  
11572 -0.135908  
11573 -0.072019  

[11574 rows x 24 columns]

In [32]:
df1.to_csv("dbs/yugi_db_polished.csv")  