In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
print("Hello World")

Hello World


In [2]:
df_yugi = pd.read_csv('dbs/yugi_comp.csv')
df_yugi = df_yugi.drop(['name'], axis=1)
df_yugi = df_yugi[df_yugi['text'].notna()]
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN  
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN  
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play  
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN  
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN

In [10]:
def getTribe(row):
    if row["card_type"] == "monster":
        return row["type"].split("/")[0].strip()
    else:
        return math.nan

In [12]:
def getEffect(row):
    if row["card_type"] == "monster":
        typ =  row["type"].split("/")[-1].strip()
        if typ == "Effect":
            return typ
        else:
            return "Normal"
    else:
        return math.nan

In [57]:
extradeckmons = ['Xyz', 'Fusion', 'Synchro', 'Ritual', 'Toon', 'Link', 'Union', 'Gemini', 'Skill']
def getMonsType(row):
    if row["card_type"] == "monster":
        typ =  row["type"].split("/")
        if len(typ) >= 3 and typ[1].strip() in extradeckmons:
            return typ[1].strip()
    else: 
        return row["type"]
    return math.nan

In [20]:
df_yugi['tribe'] = df_yugi.apply(lambda row: getTribe(row), axis=1)
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  \
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play   
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN   

           tribe effect? monsType  
0  Beast-Warrior  Effect      NaN  
1        Warrior  Effect   Effect  
2            NaN     NaN      NaN  
3          Fairy  Effect   Effect  
4         Dragon  Effect      NaN

In [21]:
df_yugi['effect?'] = df_yugi.apply(lambda row: getEffect(row), axis=1)
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  \
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play   
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN   

           tribe effect? monsType  
0  Beast-Warrior  Effect      NaN  
1        Warrior  Effect   Effect  
2            NaN     NaN      NaN  
3          Fairy  Effect   Effect  
4         Dragon  Effect      NaN

In [58]:
df_yugi['monsType'] = df_yugi.apply(lambda row: getMonsType(row), axis=1)
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  \
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play   
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN   

           tribe effect? monsType monsType2 monsType3  monsType4  
0  Beast-Warrior  Effect      NaN       NaN       NaN        NaN  
1        Warrior  Effect      Xyz    Effect       NaN        NaN  
2            NaN     NaN      NaN       NaN       NaN        NaN  
3          Fairy  Effect      Xyz    Effect       NaN        NaN  
4         Dragon  Effect      NaN       NaN       NaN        NaN

In [23]:
df_yugi.shape

(11574, 16)

In [40]:
df_yugi["monsType"].unique()

array([nan, 'Xyz', 'Tuner', 'Flip', 'Fusion', 'Pendulum', 'Synchro',
       'Ritual', 'Toon', 'Link', 'Union', 'Spirit', 'Gemini', 'Skill'],
      dtype=object)

In [81]:
extradeckmons = ['Xyz', 'Fusion', 'Synchro', 'Ritual', 'Toon', 'Link', 'Union', 'Gemini', 'Skill']

othertype  = ['Spirit', 'Continuous Spell' 'Field Spell','Flip','Continuous Trap']

def getMonsType2(row):
    monst = ""
    if type(row["type"]) is float:
        return math.nan
    #print(row["type"])
    for word in row["type"].split("/"):
            if word.strip() in othertype:
                monst += word.strip() 
    if monst == "":
        return math.nan
    else:
        return monst

In [88]:
def getMonsType3(row):
    if row["card_type"] == "monster":
        typ =  row["type"].split("/")
        for ty in typ:
            typp = ty.strip()
            if typp == "Tuner":
                return "Tuner"
        
    return math.nan

In [91]:

def getMonsType4(row):
    if row["card_type"] == "monster":
        typ =  row["type"].split("/")
        for ty in typ:
            typp = ty.strip()
            if typp == "Pendulum":
                return "Pendulum"
        
    return math.nan

In [92]:
df_yugi['monsType2'] = df_yugi.apply(lambda row: getMonsType2(row), axis=1)
df_yugi['monsType3'] = df_yugi.apply(lambda row: getMonsType3(row), axis=1)
df_yugi['monsType4'] = df_yugi.apply(lambda row: getMonsType4(row), axis=1)
df_yugi.head()

Unnamed: 0                     Name            Rarity  Price  isGood  \
0           0  XX-Saber Boggart Knight  Shatterfoil Rare   2.73    True   
1           1            Gagaga Cowboy  Shatterfoil Rare   4.68    True   
2           2        Forbidden Chalice  Shatterfoil Rare   2.09    True   
3           3         Fairy Cheer Girl  Shatterfoil Rare   2.06    True   
4           4          Exploder Dragon  Shatterfoil Rare   2.08    True   

                                                text card_type  \
0  When this card is Normal Summoned: You can Spe...   monster   
1  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2  Target 1 face-up monster on the field; until t...     spell   
3  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4  If this card is destroyed by battle and sent t...   monster   

                     type family     atk     def  level    property  \
0  Beast-Warrior / Effect  earth  1900.0  1000.0    4.0         NaN   
1  Warrior / Xyz / Effect  earth  1500.0  2400.0    4.0         NaN   
2                     NaN    NaN     NaN     NaN    NaN  Quick-Play   
3    Fairy / Xyz / Effect  light  1900.0  1500.0    4.0         NaN   
4         Dragon / Effect  earth  1000.0     0.0    3.0         NaN   

           tribe effect? monsType monsType2 monsType3 monsType4  
0  Beast-Warrior  Effect      NaN       NaN       NaN       NaN  
1        Warrior  Effect      Xyz       NaN       NaN       NaN  
2            NaN     NaN      NaN       NaN       NaN       NaN  
3          Fairy  Effect      Xyz       NaN       NaN       NaN  
4         Dragon  Effect      NaN       NaN       NaN       NaN

In [93]:
print(df_yugi["monsType"].unique())
print(df_yugi["monsType2"].unique())
print(df_yugi["Tuner?"].unique())
print(df_yugi["Pend"].unique())

[nan 'Xyz' 'Fusion' 'Synchro' 'Ritual' 'Toon' 'Link' 'Union' 'Gemini'
 'Skill']
[nan 'Flip' 'Spirit' 'Continuous Trap']
[nan 'Tuner']
[nan 'Pendulum']


In [59]:
df_yugi["monsType"].unique()

array([nan, 'Xyz', 'Fusion', 'Synchro', 'Ritual', 'Toon', 'Link', 'Union',
       'Gemini', 'Skill'], dtype=object)

In [56]:

for value in df_yugi["monsType2"].unique():
    if value in types:
        types.remove(value)
types

['Xyz',
 'Fusion',
 'Synchro',
 'Ritual',
 'Toon',
 'Link',
 'Union',
 'Gemini',
 'Skill']

## Text

In [24]:
  !pip install --upgrade tensorflow_hub

                                              0.0/100.6 kB ? eta -:--:--
     ----                                     10.2/100.6 kB ? eta -:--:--
     -------------------------------------- 100.6/100.6 kB 1.5 MB/s eta 0:00:00


In [25]:


  import tensorflow_hub as hub

  model = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")
  embeddings = model(["The rain in Spain.", "falls",
                      "mainly", "In the plain!"])

  print(embeddings.shape)  #(4,128)

(4, 128)


In [31]:
embeddings = model(["I like apple pie","I like banana bread","Volcanos are hot"])

In [33]:
embeddings

<tf.Tensor: shape=(3, 128), dtype=float32, numpy=
array([[ 9.90161598e-02, -9.63014737e-02,  9.70842987e-02,
        -3.48744914e-02,  1.13769136e-01,  5.79342954e-02,
        -1.31301492e-01, -9.20234025e-02, -2.01867819e-01,
         8.56303647e-02,  3.92870232e-02, -2.65368462e-01,
        -1.15530007e-03,  7.71153867e-02,  2.06311971e-01,
         5.87709136e-02,  3.33112366e-02,  1.37660235e-01,
         1.05344445e-01, -2.51207501e-02, -1.10472679e-01,
         1.22375771e-01, -5.70573062e-02,  2.56181732e-02,
        -1.19034044e-01, -8.53516906e-02,  5.21319583e-02,
         7.66743869e-02, -1.79157302e-01, -1.56369060e-01,
         1.22116115e-02, -2.57046353e-02, -3.48420627e-03,
         2.04930231e-01,  7.33500347e-02, -7.18652681e-02,
         1.27804130e-01, -2.45568343e-02,  1.19324073e-01,
         2.13116646e-01, -2.29718350e-02, -2.78097466e-02,
        -1.02774948e-01, -2.74781227e-01,  9.47106816e-03,
        -5.88676333e-03, -5.10715842e-02, -4.30089906e-02,
      

In [32]:
import numpy
numpy.dot(embeddings[0],embeddings[1])

1.241015

In [34]:
numpy.dot(embeddings[0],embeddings[2])

0.218732

In [36]:
embeddings=model(df_yugi["text"])

In [37]:
embeddings.shape

TensorShape([11574, 128])

In [38]:
from sklearn.decomposition import PCA

pca_yugi = PCA(n_components=5)
principalComponents_yugi = pca_yugi.fit_transform(embeddings)
principalComponents_yugi

array([[ 0.19008988,  0.24675835,  0.17741047,  0.41337516, -0.1074109 ],
       [ 0.20476273, -0.02951308, -0.44683668,  0.1064328 ,  0.23955082],
       [ 0.5857647 , -0.31468725, -0.0374322 ,  0.17344276,  0.20915574],
       ...,
       [-0.47194522, -0.11849779,  0.15841781,  0.03228849, -0.02205843],
       [-0.53394323, -0.47552239,  0.27366935, -0.09996901, -0.13566358],
       [-0.03277172, -0.35936282,  0.459244  , -0.39121027, -0.07162509]])

In [94]:
df = pd.DataFrame(principalComponents_yugi, columns=['pca1', 'pca2','pca3','pca4','pca5'])
df

pca1      pca2      pca3      pca4      pca5
0      0.190090  0.246758  0.177410  0.413375 -0.107411
1      0.204763 -0.029513 -0.446837  0.106433  0.239551
2      0.585765 -0.314687 -0.037432  0.173443  0.209156
3      0.258598  0.327651 -0.085292 -0.000707  0.274842
4      0.335081 -0.860981  0.093271 -0.375258 -0.006459
...         ...       ...       ...       ...       ...
11569 -0.589423  0.217516  0.339458 -0.278677 -0.254474
11570 -0.189615 -0.148123  0.086737  0.181324 -0.078547
11571 -0.471945 -0.118498  0.158418  0.032288 -0.022058
11572 -0.533943 -0.475522  0.273669 -0.099969 -0.135664
11573 -0.032772 -0.359363  0.459244 -0.391210 -0.071625

[11574 rows x 5 columns]

In [96]:
df1 = df_yugi.copy()
df1 = df1.join(df)
df1

Unnamed: 0                           Name            Rarity  Price  \
0               0        XX-Saber Boggart Knight  Shatterfoil Rare   2.73   
1               1                  Gagaga Cowboy  Shatterfoil Rare   4.68   
2               2              Forbidden Chalice  Shatterfoil Rare   2.09   
3               3               Fairy Cheer Girl  Shatterfoil Rare   2.06   
4               4                Exploder Dragon  Shatterfoil Rare   2.08   
...           ...                            ...               ...    ...   
11642       11642        Herald of Mirage Lights        Ultra Rare   1.55   
11643       11643   Graveyard of Wandering Souls        Ultra Rare   1.39   
11644       11644  Lib the World Key Blademaster        Ultra Rare   3.47   
11645       11645                   Kingyo Sukui        Ultra Rare   1.22   
11646       11646               Skydive Scorcher        Ultra Rare   1.58   

       isGood                                               text card_type  \
0        True  When this card is Normal Summoned: You can Spe...   monster   
1        True  2 Level 4 monsters\n\nOnce per turn: You can d...   monster   
2        True  Target 1 face-up monster on the field; until t...     spell   
3        True  2 Level 4 Fairy-Type monsters\n\nYou can detac...   monster   
4        True  If this card is destroyed by battle and sent t...   monster   
...       ...                                                ...       ...   
11642   False  2 monsters with the same Type and Attribute, e...   monster   
11643   False  If this card is already face-up on the field:\...      trap   
11644   False  2 monsters\n\nCan only be Link Summoned while ...   monster   
11645   False  You can target 1 monster in your opponent's GY...      trap   
11646   False  Target 1 "Elemental HERO" Fusion Monster you c...     spell   

                          type family     atk  ...  effect?  monsType  \
0       Beast-Warrior / Effect  earth  1900.0  ...   Effect       NaN   
1       Warrior / Xyz / Effect  earth  1500.0  ...   Effect       Xyz   
2                          NaN    NaN     NaN  ...      NaN       NaN   
3         Fairy / Xyz / Effect  light  1900.0  ...   Effect       Xyz   
4              Dragon / Effect  earth  1000.0  ...   Effect       NaN   
...                        ...    ...     ...  ...      ...       ...   
11642    Fairy / Link / Effect  light   600.0  ...   Effect      Link   
11643                      NaN    NaN     NaN  ...      NaN       NaN   
11644  Cyberse / Link / Effect  light  2000.0  ...   Effect      Link   
11645                      NaN    NaN     NaN  ...      NaN       NaN   
11646                      NaN    NaN     NaN  ...      NaN       NaN   

      monsType2 monsType3 monsType4      pca1      pca2      pca3      pca4  \
0           NaN       NaN       NaN  0.190090  0.246758  0.177410  0.413375   
1           NaN       NaN       NaN  0.204763 -0.029513 -0.446837  0.106433   
2           NaN       NaN       NaN  0.585765 -0.314687 -0.037432  0.173443   
3           NaN       NaN       NaN  0.258598  0.327651 -0.085292 -0.000707   
4           NaN       NaN       NaN  0.335081 -0.860981  0.093271 -0.375258   
...         ...       ...       ...       ...       ...       ...       ...   
11642       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
11643       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
11644       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
11645       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
11646       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

           pca5  
0     -0.107411  
1      0.239551  
2      0.209156  
3      0.274842  
4     -0.006459  
...         ...  
11642       NaN  
11643       NaN  
11644       NaN  
11645       NaN  
11646       NaN  

[11574 rows x 24 columns]